version: '3.8'

services:
  app-server:
    # 关键点 1：指定构建上下文为当前目录
    build:
      context: .
      dockerfile: Dockerfile
    # 关键点 2：构建后的镜像名
    image: ha-springboot:latest
    container_name: monolith-app
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      # 用双引号把这一长串包起来，防止空格或特殊字符解析翻车
      - JAVA_OPTS=-Xms512m -Xmx512m -XX:StartFlightRecording=disk=true,repository=/tmp/jfr_repo,filename=/app/logs/recording-%t.jfr,dumponexit=true
      - SPRING_PROFILES_ACTIVE=prod

    restart: always
    healthcheck:
      # 建议：如果 curl 不通，尝试使用 wget -q --spider http://localhost:9090/actuator/health
      test: ["CMD", "curl", "-f", "http://localhost:9090/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 45s # 考虑到 JFR 启动会有额外开销，稍微放宽一点
    volumes:
      - ./logs:/app/logs
      - ./jfr_repo:/tmp/jfr_repo
    networks:
      - monitor-net

  # 3. Prometheus 监控服务
  prometheus:
    image: prom/prometheus:v3.9.1
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9000:9090" # 避免和应用管理端口 9090 冲突
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitor-net
    depends_on:
      - app-server

  grafana:
    image: grafana/grafana-oss:12.4.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitor-net
    depends_on:
      - prometheus
    restart: unless-stopped

networks:
  monitor-net:
    driver: bridge

volumes:
  grafana-storage:
